const video=document.querySelector('#video'),canvas=document.querySelector('#canvas'),ctx=canvas.getContext('2d',{willReadFrequently:true});
const $=s=>document.querySelector(s); let stream=null,running=false,busy=false,track=null,lastSeen='',lastAt=0; const codes=[];
const formats=['Code128','Code39','Code93','Codabar','EAN13','EAN8','ITF','UPCA','UPCE'];
function status(t){$('#status').textContent=t} function render(){ $('#count').textContent=codes.length; $('#items').className=codes.length?'':'empty'; $('#items').innerHTML=codes.length?codes.map((x,i)=>`<div class="row"><span>${x.text}<small>${x.format||'Código de barras'}</small></span><span>${String(i+1).padStart(2,'0')}</span></div>`).join(''):'Todavía no hay códigos leídos.' }
async function start(){try{stop();stream=await navigator.mediaDevices.getUserMedia({audio:false,video:{facingMode:{ideal:'environment'},width:{ideal:1920},height:{ideal:1080}}});video.srcObject=stream;track=stream.getVideoTracks()[0];await video.play();running=true;setupCaps();status('Apunta el código dentro del marco');scan()}catch(e){status('No se pudo abrir la cámara: '+e.message)}}
function stop(){running=false;if(stream)stream.getTracks().forEach(t=>t.stop());stream=null;track=null;video.srcObject=null;$('#torch').disabled=true;$('#zoom').disabled=true}
function setupCaps(){if(!track?.getCapabilities)return;const c=track.getCapabilities();if(c.torch)$('#torch').disabled=false;if(c.zoom){const z=$('#zoom');z.min=c.zoom.min;z.max=c.zoom.max;z.step=c.zoom.step||.1;z.value=track.getSettings().zoom||c.zoom.min;z.disabled=false}}
async function scan(){if(!running)return;if(!busy&&video.readyState>=2){busy=true;try{const vw=video.videoWidth,vh=video.videoHeight;const sx=Math.round(vw*.05),sy=Math.round(vh*.32),sw=Math.round(vw*.90),sh=Math.round(vh*.36);canvas.width=sw;canvas.height=sh;ctx.drawImage(video,sx,sy,sw,sh,0,0,sw,sh);const data=ctx.getImageData(0,0,sw,sh);const res=await ZXingWASM.readBarcodes(data,{formats,tryHarder:true,tryRotate:true,tryInvert:true,maxNumberOfSymbols:1});if(res?.length)accept(res[0])}catch(e){}finally{busy=false}}setTimeout(scan,110)}
function accept(r){const text=(r.text||'').trim();if(!text)return;const now=Date.now();if(text===lastSeen&&now-lastAt<1800)return;lastSeen=text;lastAt=now;$('#last').textContent=text;$('#format').textContent=r.format||'';if(!codes.some(x=>x.text===text)){codes.unshift({text,format:r.format});render();navigator.vibrate?.(80);status('✓ Código leído: '+text)}else status('Código ya incluido: '+text)}
$('#start').onclick=start;$('#stop').onclick=()=>{stop();status('Cámara cerrada')};$('#clear').onclick=()=>{codes.length=0;render();$('#last').textContent='—';$('#format').textContent=''};
$('#torch').onclick=async()=>{if(!track)return;const on=$('#torch').dataset.on!=='1';try{await track.applyConstraints({advanced:[{torch:on}]});$('#torch').dataset.on=on?'1':'0';$('#torch').textContent=on?'🔦 Apagar':'🔦 Linterna'}catch(e){status('La linterna no está disponible')}};
$('#zoom').oninput=async e=>{try{await track?.applyConstraints({advanced:[{zoom:Number(e.target.value)}]})}catch{}};
window.addEventListener('pagehide',stop);render();
